### PR TITLE
Enforce schema validation on pre-commit.

### PR DESCRIPTION
**Pull request by amrc-benmorrow**
We are wasting too much time committing invalid schemas. Set up a pre-commit hook which enforces validity.

### CODE REVIEW

**Comment by Kallb123** [comment]
Since you're on GH.com you could run this as an Action on any PRs? It wouldn't let you merge invalid branches then

**Comment by amrc-benmorrow** [comment]
@Kallb123 Yes, maybe... I find GH actions annoying to set up :). I think we'd want to leave it as a `pre-commit` hook in any case, as it saves time pushing invalid code just to have the merge rejected.

**Comment by Kallb123** [comment]
It is pretty wasteful to push and then find it's failed. How do you actually distribute or enforce a client-side hook though? Since they're not in the repo, do you share it separately?

**Comment by amrc-benmorrow** [comment]
OK, I'm being stupid; I hadn't realised this hadn't committed the `.git/hooks/pre-commit` script. Let me look a little further...

**Comment by AlexGodbehere** [comment]
Github Action added.

**Review by AlexGodbehere — APPROVED** [review]

**Pull request merged**
